### ISSUE TITLE
Private Key in repository

### ISSUE THREAD

**Issue by chmey** [ShraxO1/Peek#2]
**Problem**
I've noticed a private key wa committed to this repository.

**Supposed solution**
I'd like to address this issue by removing/purging the private key and its certificate from the repository and adding a startup script to generate a certificate and private key pair.

**Comment by ShraxO1** [comment]
Go ahead.

**Comment by chmey** [comment]
Please check the PR https://github.com/ShraxO1/Peek/pull/5 then.
